environment: prod

elasticConfiguration:
  host : hubsystem-app-10.nm.flipkart.com
  port : 9300
  clusterName : elasticsearch

server:
  applicationConnectors:
    - type: http
      port: 27015
  minThreads: 100

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  loggers:
    com.flipkart: INFO
    org.hibernate.SQL: ERROR

  appenders:
    - type: console
    - type: file
      currentLogFilename: /var/log/flipkart/supply_chain/resource-management-service/service.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: /var/log/flipkart/supply_chain/resource-management-service/service-%d{yyyy-MM-dd}.log
      archivedFileCount: 30
      timeZone: IST
      logFormat: "%highlight(%-5level) [%date] [%thread] [%cyan(%logger{0})]: %message%n"

swagger:
  resourcePackage: resources.management.service.resources
